# Global configuration
root_dir = "$cfg_dir" # optional - can be used as a variable in process paths
log_level = "trace" # trace,debug,info,warn,error
port_range_start = 4200 # will start serving on 4200 and up 1 for each site
default_log_format = "standard" # optional: "dotnet" or "standard"
env_vars = [
     # can be overridden by site specific ones
     { key = "env_var_for_all_sites" , value = "nice" }, 
]
#port=8000 # 80 is default

# Normal host
[[processes]]
host_name = "fun.local"
path = "$root_dir\\sites\\fun"
bin = "my_site.exe"
args = ["/woohoo"]
https = false # optional bool
log_format = "standard" # optional - overrides default_log_format if defined
env_vars = [
    { key = "site_specific_env_var", value = "hello"},
]

# Host a node based site
[[processes]]
host_name = "noodle.local"
path = "c:\\temp"
bin = "node"
args = ["app.js"]
env_vars = []

# Hosting an asp.net 4.8 based site behind IIS express 
[[processes]]
host_name = "cool-site.local"
path = "C:\\Program Files\\IIS Express"
bin = "iisexpress.exe"
args = [ 
    "/path:c:\\temp\\cool-site", 
    "/port:12345",
    "/hostname:127.0.0.1",
    "/trace:error"]
env_vars = [
    # since port was configured in an arg, we need to also specify it here
    # to override the otherwise automatic port configuration
    { key = "port", value = "12345"},
]
