version = "V2"
alpn = false
http_port = 8080
admin_api_port = 1234
ip = "127.0.0.1"
tls_port = 4343
auto_start = false
root_dir = "~"
log_level = "trace"
port_range_start = 4200
default_log_format = "standard"
env_vars = [
	{ key = "GRPC_TRACE", value = "http,http1,http_keepalive,http2_stream_state" },
	{ key = "GRPC_VERBOSITY", value = "DEBUG" },
]

[[remote_target]]
host_name = "caddy-lb-terminated.localtest.me"
disable_tcp_tunnel_mode = true
backends = [
	{ address="127.0.0.1", port=9999, hints = ['NOH2']},
	{ address="127.0.0.1", port=8888, hints = ['NOH2']}
]

[[remote_target]]
host_name = "caddy-lb-tcp.localtest.me"
backends = [
	{ address="127.0.0.1", port=9999},
	{ address="127.0.0.1", port=8888}
]

[[remote_target]]
host_name = "lobsters.localtest.me"
disable_tcp_tunnel_mode = true
backends = [
	{ https = true, address="lobste.rs", port=443},
	{ address="nnerastoundinglushmorning.neverssl.com", port=80}
]

[[hosted_process]]
host_name = "caddy-proc-terminated.localtest.me"
disable_tcp_tunnel_mode = true
dir = "$cfg_dir"
bin = "/nix/store/aq5r61lmr9six0lyi6xikxwvnyp16dfy-user-environment/bin/caddy"
hints = [
'NOH2'
]
args = [
  "run", 
  "--config", 
  "./CaddyTest2", 
  "--adapter", 
  "caddyfile"
]
auto_start = true
port = 8888

[[hosted_process]]
host_name = "caddy-proc-tcp.localtest.me"
dir = "$cfg_dir"
bin = "/nix/store/aq5r61lmr9six0lyi6xikxwvnyp16dfy-user-environment/bin/caddy"
hints = [
'NOH2'
]
args = [
  "run", 
  "--config", 
  "./CaddyTest1", 
  "--adapter", 
  "caddyfile"
]
auto_start = true
port = 9999
