#:schema https://raw.githubusercontent.com/OlofBlomqvist/odd-box/main/odd-box-schema-v2.json

version = "V2" 
root_dir = "~"
log_level = "Info" 
port_range_start = 4200
env_vars = []

[[remote_target]] 
host_name = "lobsters.localtest.me" 
backends = [ 
    { address = "lobste.rs", port = 443, https = true } , 
    { address = "lobsters.dev", port = 443, https = true }
]

[[hosted_process]]
host_name = "py.localtest.me"
dir = "$cfg_dir"
bin = "/usr/bin/python3"
args = ["-m", "http.server", "$port"]
port = 8012
env_vars = []