version = "V1" 
root_dir = "~"
log_level = "info" 
port_range_start = 4200
env_vars = []

[[remote_target]] 
host_name = "lobsters.localtest.me" 
target_hostname = "lobste.rs"

[[hosted_process]]
host_name = "py.localtest.me"
dir = "$cfg_dir"
bin = "/usr/bin/python3"
args = ["-m", "http.server", "8012"]
port = 8012
env_vars = []