name: Manually Upload Artifacts to Release

on:
  workflow_dispatch:
    inputs:
      releaseID:
        description: 'Release ID'
        required: true
      runID:
        description: 'Run ID'
        required: true

jobs:
  upload-artifacts:
  
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Download artifacts from a specific run ID
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        run-id: ${{ github.event.inputs.runID }}

    # Upload the downloaded artifacts to the release
    - name: Upload Artifacts to Release
      run: |
        for artifact in $(ls -1); do
          gh release upload ${{ github.event.inputs.releaseID }} "$artifact/*"
        done
