name: Build and Release

on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Release name to attach the artifacts to'
        required: true

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}
  
jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: ${{ matrix.target }}
        profile: minimal
        override: true

    - name: Build
      run: cargo build --release --verbose --target ${{ matrix.target }}
    
    - name: Upload Artifact to GitHub
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          gh release upload "${{ github.event.inputs.releaseName }}" target/${{ matrix.target }}/release/odd-box.exe "odd-box-${{ matrix.target }}.exe"
        else
          gh release upload "${{ github.event.inputs.releaseName }}" target/${{ matrix.target }}/release/odd-box "odd-box-${{ matrix.target }}.bin"
        fi
