name: Build and Release

on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Release name to attach the artifacts to'
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
    - name: Build
      run: cargo build --release --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-artifact
        path: target/release/odd-bo*

  upload-release-assets:
    needs: build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2
    - name: Install gh
      run: sudo apt install -y gh
    - name: Upload Artifacts to Release
      run: |
        cd /home/runner/work/odd-box/odd-box/
        ls
        echo "..."
        ls -1
        echo "..."
        for artifact in $(ls -1); do
          if [ -d "$artifact" ]; then
            cd "$artifact"
            for file in $(ls -1); do
              gh release upload "${{ github.event.inputs.releaseName }}" "$file"
            done
            cd ..
          fi
        done
      
