name: Build and Release

on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Release name to attach the artifacts to'
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
    - name: Build
      run: cargo build --release --verbose
    - name: Upload Artifact to GitHub
      run: |
        gh release upload "${{ github.event.inputs.releaseName }}" target/release/odd-bo*
